environment:
  matrix:
  - nodejs_version: "7"
  - nodejs_version: "6"
  - nodejs_version: "5"
  - nodejs_version: "4"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

cache:
  - "%LOCALAPPDATA%\\Yarn"

test_script:
  - node --version
  - npm --version
  - npm run test:CI

build: off

notifications:
- provider: Email
  to:
  - housecor@gmail.com
  subject: 'Build failed: react-slingshot'
  message: The continuous integration build failed. See https://ci.appveyor.com/project/CoryHouse/react-slingshot/ for details.
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
