export const PLAY_PROJECT = 'PLAY_PROJECT';
export const STOP_PROJECT = 'STOP_PROJECT';
export const INCREMENT_LIVE_NODE = 'INCREMENT_LIVE_NODE';
export const LOOP_LIVE_NODE = 'LOOP_LIVE_NODE';
export const RECORD_START = 'RECORD_START';
export const PLAY_PROJECT_LIVE_DONE = 'PLAY_PROJECT_LIVE_DONE';
export const AUDIO_DOWNLOADED = 'AUDIO_DOWNLOADED'; 